// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbbXra8rNyamqmGvohuLS0nVk3oiFzScQ',
    appId: '1:943225215328:web:ee9163266ea5aec3ff2605',
    messagingSenderId: '943225215328',
    projectId: 'kickoff-69472',
    authDomain: 'kickoff-69472.firebaseapp.com',
    databaseURL: 'https://kickoff-69472-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kickoff-69472.appspot.com',
    measurementId: 'G-57KZZ0RZFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBci9EWVAgppq-yNHoenPjIlvTrZCnRCZE',
    appId: '1:943225215328:android:8f6b861188f50a6cff2605',
    messagingSenderId: '943225215328',
    projectId: 'kickoff-69472',
    databaseURL: 'https://kickoff-69472-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kickoff-69472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkQcjiMI31iGIDF6vJWElPjX9l8ja6xsI',
    appId: '1:943225215328:ios:622e169909513f05ff2605',
    messagingSenderId: '943225215328',
    projectId: 'kickoff-69472',
    databaseURL: 'https://kickoff-69472-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kickoff-69472.appspot.com',
    iosBundleId: 'com.example.takwira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkQcjiMI31iGIDF6vJWElPjX9l8ja6xsI',
    appId: '1:943225215328:ios:622e169909513f05ff2605',
    messagingSenderId: '943225215328',
    projectId: 'kickoff-69472',
    databaseURL: 'https://kickoff-69472-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kickoff-69472.appspot.com',
    iosBundleId: 'com.example.takwira',
  );
}
