class TunisiaLocations {
  //https://www.tunisieindustrie.nat.tn/fr/doc.asp?mcat=13&mrub=105
  static const String country = "Tunisie";

  static const List<String> states = [
    'Ariana',
    'Béja',
    'Ben Arous',
    'Bizerte',
    'Gabès',
    'Gafsa',
    'Jendouba',
    'Kairouan',
    'Kasserine',
    'Kébili',
    'Le Kef',
    'Mahdia',
    'Manouba',
    'Médenine',
    'Monastir',
    'Nabeul',
    'Sfax',
    'Sidi Bouzid',
    'Siliana',
    'Sousse',
    'Tataouine',
    'Tozeur',
    'Tunis',
    'Zaghouan',
  ];

  static const Map<String, List<String>> citiesBystates = {
    'Ariana': [
      'Ariana',
      'Ettadhamen-Mnihla',
      'Raoued',
      'Sidi Thabet',
      'Kalâat el-Andalous',
      'La Soukra'
    ],
    'Béja': [
      'Béja',
      'Medjez el-Bab',
      'Testour',
      'Thibar',
      'El Maâgoula',
      'Goubellat',
      'Nefza',
      'Téboursouk',
      'Zahret Medien'
    ],
    'Ben Arous': [
      'Ben Arous',
      'Mohamedia-Fouchana',
      'Hammam Lif',
      'Hammam Chott',
      'Megrine',
      'Bou Mhel el-Bassatine',
      'Ezzahra',
      'Khalidia',
      'Mornag',
      'Radès',
    ],
    'Bizerte': [
      'Bizerte',
      'Menzel Bourguiba',
      'Mateur',
      'Ras Jebel',
      'Ghar al Milh',
      'Aousja',
      'El Alia',
      'Ghar El Melh',
      'Menzel Abderrahmane',
      'Menzel Jemil',
      'Metline',
      'Raf Raf',
      'Sejnane',
      'Tinja',
    ],
    'Gabès': [
      'Gabès',
      'El Hamma',
      'Mareth',
      'Metouia',
      'Chenini Nahal',
      'Ghannouch',
      'Mareth',
      'Matmata',
      'Nouvelle Matmata',
      'Oudhref',
      'Zarat'
    ],
    'Gafsa': [
      'Gafsa',
      'El Ksar',
      'Moulares',
      'Redeyef',
      'El Guettar',
      'Mdhila',
      'Metlaoui',
      'Sened'
    ],
    'Jendouba': [
      'Jendouba',
      'Tabarka',
      'Ain Draham',
      'Fernana',
      'Beni M’Tir',
      'Bou Salem',
      'Ghardimaou',
      'Oued Melliz'
    ],
    'Kairouan': [
      'Kairouan',
      'Haffouz',
      'Oueslatia',
      'Bou Hajla',
      'Alaâ',
      'Chebika',
      'Echrarda',
      'Hajeb El Ayoun',
      'Menzel Mehiri',
      'Nasrallah',
      'Sbikha'
    ],
    'Kasserine': [
      'Kasserine',
      'Feriana',
      'Sbeitla',
      'Thala',
      'Fériana',
      'Foussana',
      'Haïdra',
      'Jedelienne',
      'Magel Bel Abbès',
      'Sbiba',
      'Thélepte'
    ],
    'Kébili': ['Kébili', 'Douz', 'Souk Lahad', 'Djemna', 'El Golâa'],
    'Le Kef': [
      'Le Kef',
      'Dahmani',
      'Sakiet Sidi Youssef',
      'Tajerouine',
      'El Ksour',
      'Jérissa',
      'Kalaa  Khasba',
      'Kalaat es Senam',
      'Kef',
      'Menzel Salem',
      'Nebeur',
      'Sers',
      'Touiref'
    ],
    'Mahdia': [
      'Mahdia',
      'Bou Merdes',
      'Chebba',
      'El Jem',
      'Chorbane',
      'El Bradâa',
      'Essouassi',
      'Hebira',
      'Ksour Essef',
      'Melloulèche',
      'Ouled Chamekh',
      'Rejiche',
      'Sidi Alouane'
    ],
    'Manouba': [
      'Manouba',
      'Douar Hicher',
      'Djedeida',
      'Oued Ellil',
      'Borj El Amri',
      'Den Den',
      'El Battan',
      'Mornaguia',
      'Tebourba'
    ],
    'Médenine': [
      'Médenine',
      'Ben Gardane',
      'Djerba Midoun',
      'Zarzis',
      'Ajim',
      'Beni Khedache',
      'Houmt El Souk',
      'Midoun'
    ],
    'Monastir': [
      'Monastir',
      'Moknine',
      'Jemmal',
      'Ksar Hellal',
      'Amiret El Fhoul',
      'Amiret El Hojjaj',
      'Amiret Touazra',
      'Bekalta',
      'Bembla',
      'Benen Bodher',
      'Béni Hassen',
      'Bouhjar',
      'Cherahil',
      'Ghenada',
      'Jemmal',
      'Khniss',
      'Ksar Hellal',
      'Ksibet El Mediouni',
      'Lemta',
      'Menzel Ennour',
      'Menzel Farsi',
      'Menzel Hayet',
      'Menzel Kamel',
      'Moknine',
      'Ouerdanin',
      'Sahline Moôtmar',
      'Sayada',
      'Sidi Ameur',
      'Sidi Bennour',
      'Téboulba',
      'Touza',
      'Zéramdine',
    ],
    'Nabeul': [
      'Nabeul',
      'Hammamet',
      'Kelibia',
      'Soliman',
      'Dar Chaabane',
      'Azmour',
      'Béni Khalled',
      'Béni Khiar',
      'Bou Argoub',
      'Dar Allouch',
      'El Haouaria',
      'El Maâmoura',
      'Grombalia',
      'Hammam Ghezèze',
      'Kelibia',
      'Korba',
      'Korbous',
      'Menzel Bouzelfa',
      'Menzel Horr',
      'Menzel Temime',
      'El Mida',
      'Somâa',
      'Takelsa',
      'Tazerka',
      'Zaouiet Djedidi'
    ],
    'Sfax': [
      'Sfax',
      'Sakiet Ezzit',
      'Menzel Chaker',
      'El Hencha',
      'Agareb',
      'Bir Ali Ben Khélifa',
      'Chihia',
      'El Ain',
      'Ghraïba',
      'Gremda',
      'Jebiniana',
      'Kerkennah',
      'Mahares',
      'Sakiet Eddaïer',
      'Skhira',
      'Thyna'
    ],
    'Sidi Bouzid': [
      'Sidi Bouzid',
      'Regueb',
      'Jilma',
      'Cebbala Ouled Asker',
      'Bir El Hafey',
      'Cebalet',
      'Jilma',
      'Meknassy',
      'Menzel Bouzaiane',
      'Mezzouna',
      'Ouled Haffouz',
      'Regueb',
      'Sidi Ali Ben Aoun'
    ],
    'Siliana': [
      'Siliana',
      'Maktar',
      'Bouarada',
      'Gaafour',
      'Bargou',
      'Bou Arada',
      'El Aroussa',
      'El Krib',
      'Gaâfour',
      'Kesra',
      'Maktar',
      'Rouhia',
      'Sidi Bou Rouis'
    ],
    'Sousse': [
      'Sousse',
      'M\'saken',
      'Kalaa Kebira',
      'Akouda',
      'Bouficha',
      'Ezzouhour',
      'Enfidha',
      'Hammam Sousse',
      'Hergla',
      'Kalaa Kebira',
      'Kalaa Seghira',
      'Kondar',
      'Ksibet Thrayet',
      'Messaadine',
      'M"saken',
      'Sidi Bou Ali',
      'Sidi El Hani',
      'Zaouiet Sousse'
    ],
    'Tataouine': [
      'Tataouine',
      'Ghomrassen',
      'Bir Lahmar',
      'Dehiba',
      'Remada',
      'Sammar'
    ],
    'Tozeur': [
      'Tozeur',
      'Nefta',
      'Degache',
      'Hamet El Dabab',
      'Degache',
      'Hamet Jerid',
      'Nafta',
      'Tamerza',
    ],
    'Tunis': [
      'Tunis',
      'Carthage',
      'La Goulette',
      'La Marsa',
      'Le Bardo',
      'Le Kram',
      'Sidi Bou Said',
      'Sidi Hassine'
    ],
    'Zaghouan': [
      'Zaghouan',
      'Zriba',
      'El Fahs',
      'Nadhour',
      'Bir Mcherga',
      'Djebel Oust'
    ],
  };
}
